### ISSUE TITLE
Add lanelet2 map files to a resource folder

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_osm#2]
### Summary

Provide lanelet2 maps. 

1-lane roads:
- [x] Straight lane road
- [x] Arc Lane Road
- [x] Elevated Roads
- [x] Super elevated road

n-lane roads:
- [x] T Shape road. 
- [x] Straight road.

### Suggestion

maliput_malidrive's xodr files should work as inspiration for the maps to provide.

**Comment by francocipollone** [comment]
It tried to create a version of the[ `ParkingGarageRamp.xodr` ](https://github.com/maliput/maliput_malidrive/blob/814882a828feded7949e51d7eeef6414a2b701f5/resources/ParkingGarageRamp.xodr#L34)for this backend:

`maliput_malidrive` view:
![image](https://user-images.githubusercontent.com/53065142/195363516-b3e7db83-8f77-4907-a2d7-4e3f8a5a01a3.png)

**Note that this map is a 2-lane road map with no connections.**

So I converted it to .osm file using a sample step of 1m.
[lanelet2_parking_garage_ramp.zip](https://github.com/maliput/maliput_osm/files/9765564/lanelet2_parking_garage_ramp.zip)



This is the view using a 2D visualizer (JOSM)

![image](https://user-images.githubusercontent.com/53065142/195364249-f617215b-def4-4d96-8b2c-4a4ed97b165e.png)

However when trying to load it using `maliput_osm` the visualization is quiiite different:

![image](https://user-images.githubusercontent.com/53065142/195365494-fc108347-6caf-4d3b-b5a8-9c06a456f3c4.png)

After debugging for a while this seems to be happening because of a limitation in the algorithm we are using (lanelet2-based) for computing the centerline given left and right linestrings. ([geometry/utility/geometry.cc](https://github.com/maliput/maliput_sparse/blob/main/src/geometry/utility/geometry.cc))
Which happens to behave this way(algorithm fails) **when there is some overlapping for the same lane in the xy projection.**()

So If we were to continue porting this ParkingGarageRamp we should split the lane into two before it starts to overlap.

**Comment by liangfok** [comment]
> limitation in the algorithm we are using (lanelet2-based) for computing the centerline given left and right linestrings. ([geometry/utility/geometry.cc](https://github.com/maliput/maliput_sparse/blob/main/src/geometry/utility/geometry.cc))
Which happens to behave this way(algorithm fails) when there is some overlapping for the same lane in the xy projection.()

Let's file a ticket upstream.

**Comment by francocipollone** [comment]
> > limitation in the algorithm we are using (lanelet2-based) for computing the centerline given left and right linestrings. ([geometry/utility/geometry.cc](https://github.com/maliput/maliput_sparse/blob/main/src/geometry/utility/geometry.cc))
> > Which happens to behave this way(algorithm fails) when there is some overlapping for the same lane in the xy projection.()
> 
> Let's file a ticket upstream.

Done! -> https://github.com/fzi-forschungszentrum-informatik/Lanelet2/issues/260
