### ISSUE TITLE
Populates RoadNetwork with providers

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_osm#36]
### Summary

Populate providers for discrete, range value rules, and phases

### Suggestions

- Target only the new rule api.

### State
- [x] PhaseProvider
- [x] DiscreteValueRuleStateProvider
- [x] RangeValueRuleStateProvider

Related to #12

**Comment by francocipollone** [comment]
Same thing for hte Discrete and Range ValueRuleState providers:
 - https://github.com/maliput/maliput_malidrive/blob/73533b637c6bd635408100299a26204a767ff5a2/src/maliput_malidrive/builder/discrete_value_rule_state_provider_builder.cc#L38-L60
 - https://github.com/maliput/maliput_malidrive/blob/73533b637c6bd635408100299a26204a767ff5a2/src/maliput_malidrive/builder/range_value_rule_state_provider_builder.cc#L38-L60

**Comment by agalbachicar** [comment]
> That way we also avoid duplicating code. wdyt? @agalbachicar .

Aye! Let's move it down to maliput-base

**Comment by francocipollone** [comment]
Tasks
 - [ ] Add default initialization for the ManualPhaseProvider. https://github.com/maliput/maliput/pull/530
 - [ ] Add default initialization for the DiscreteRuleStateProvider
 - [ ] Add default initialization for the RangeRuleStateProvider
